version: '3.2'

services:
  alleventpictures-aacc:
    image: postgres:17
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin753951
      - POSTGRES_DB=AllEventPictures
    ports:
      - "5468:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped
    networks:
      - event-aacc-network

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8081" # Expose port 8081 of the FastAPI app on port 8082 of the host
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:admin753951@alleventpictures-aacc:5432/AllEventPictures
    depends_on:
      - alleventpictures-aacc
    restart: unless-stopped
    networks:
      - event-aacc-network

networks:
  event-aacc-network:
    driver: bridge
volumes:
  postgres_data:
