version: '3.8'

services:
  eventphoto-aacc:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passadmin
      - POSTGRES_DB=EventPhoto
    ports:
      - "5468:5432"
    volumes:
      - .:/opt/eventphoto
    restart: unless-stopped
    networks:
      - event-aacc-network

networks:
  event-aacc-network:
    driver: bridge
