version: '3.8'

services:
  alleventpictures-aacc:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin753951
      - POSTGRES_DB=AllEventPictures
    ports:
      - "5468:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - event-aacc-network

networks:
  event-aacc-network:
    driver: bridge
